### PR TITLE
Review visualization notebooks

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Remarks for the matplotlib notebook:

- I would change the language about the style a bit (the default is not that bad anymore, and also no longer resembling matlab)

- The 

```
fig, ax = plt.subplots(figsize=(16, 6))
ax.plot(flowdata.index, flowdata["L06_347"],
        flowdata.index, flowdata["LS06_347"], 
        flowdata.index, flowdata["LS06_348"])
ax.legend(["L06_347", "LS06_347", "LS06_348"])
```

can in principle be replaced with

```
fig, ax = plt.subplots(figsize=(16, 6))
ax.plot(flowdata)
ax.legend(["L06_347", "LS06_347", "LS06_348"])
```

**Comment by stijnvanhoey** [comment]
I adapted the descriptions and story-line to match the current state of matplotlib :-)

**Comment by stijnvanhoey** [comment]
Ready to merge!

**Comment by jorisvandenbossche** [comment]
@stijnvanhoey Can you just do a "restart kernel and run all" to make sure there are no problems with the numbering?

**Comment by stijnvanhoey** [comment]
restart & run all done!

**Pull request merged**
